### ISSUE TITLE
can't add an installed application to the list

### ISSUE THREAD

**Issue by Chr1sis** [crystalidea/uninstall-tool#67] opened 2021-08-28 15:18 UTC
I've removed an application's entry mistakenly and I'm wondering how I could re-add it without reinstalling the application again

**Comment by kleuter** [comment] 2021-08-29 07:11
There's no backup made when removing an entry manually from the list, you'd have to reinstall this app again I'm afraid

**Comment by Chr1sis** [comment] 2021-08-30 14:50
Thanks for your reply, it would be appreciated if you guys add a function that allows users to choose a folder to re-add an app to the list manually.XD

**Comment by kleuter** [comment] 2022-10-20 09:33
Duplicate of https://github.com/crystalidea/uninstall-tool/issues/68

**Closed by kleuter** 2022-10-20 09:33 UTC
