### ISSUE TITLE
Can't click the uninstall button

### ISSUE THREAD

**Issue by 623738576** [crystalidea/uninstall-tool#121] opened 2022-12-28 02:21 UTC
The tracked data is so long that I can’t click the uninstall button when uninstalling this software, because there are too many names of software that need to be uninstalled, and I can’t click the uninstall button

**Comment by kleuter** [comment] 2024-04-03 14:57
Duplicate of https://github.com/crystalidea/uninstall-tool/issues/73

**Closed by kleuter** 2024-04-03 14:57 UTC
Labels: bug
