### ISSUE TITLE
NvCplDesktopContextDisabled 3.6.1 win7x64

### ISSUE THREAD

**Issue by ruboard** [crystalidea/uninstall-tool#109] opened 2022-08-19 21:40 UTC
I install the program, rmb  the nvidia panel disappears on the desktop. delete registry key
HKEY_CLASSES_ROOT\Directory\Background\shellex\ContextMenuHandlers\NvCplDesktopContext]
@="{A70C977A-BF00-412C-90B7-034C51DA2439} , rmb track is. 
I restore the key, - the rmb disappears to track.

also in the registry:
 [HKEY_CLASSES_ROOT\CLSID\{FE8E6AD6-DABE-45e1-88C2-48DC4578924C}]
@="UTShellExt"
"NvCplDesktopContextDisabled"=dword:00000001
 
[HKEY_CLASSES_ROOT\CLSID\{FE8E6AD6-DABE-45e1-88C2-48DC4578924C}\InProcServer32]
@="C:\\Program Files\\Uninstall Tool\\utshellext.dll"
"ThreadingModel"="Apartment" 

that is, either this or that

**Comment by kleuter** [comment] 2022-08-20 07:15
Duplicate of https://github.com/crystalidea/uninstall-tool/issues/107

**Closed by kleuter** 2022-08-20 07:15 UTC
