### ISSUE TITLE
Uninstall Tool is preventing Windows 10 from pinning shortcuts to start menu

### ISSUE THREAD

**Issue by plumduffer** [crystalidea/uninstall-tool#101] opened 2022-07-16 05:54 UTC
This started happening today after installing Uninstall Tool.

I was installing apps and pinning them to the start menu via the desktop shortcut, and this suddenly stopped working after installing Uninstall Tool.

This is the latest version 3.6.1

**Comment by kleuter** [comment] 2022-07-16 06:30
Also it's impossible to launch any desktop shortcut under administrator
This is very strange.

**Comment by kleuter** [comment] 2022-07-16 06:33
Somehow it's caused by utshellext.dll, current workaround is to disable it by running
`regsvr32 /u utshellext.dll`

**Comment by plumduffer** [comment] 2022-07-16 06:42
> Somehow it's caused by utshellext.dll, current workaround is to disable it by running `regsvr32 /u utshellext.dll`

Thanks for the prompt response, will keep using this version as it's not a huge deal. Looking forward to having a fix in the future, though. Keep up the great work!

**Comment by kleuter** [comment] 2022-07-30 14:49
Fixed in the latest download, thanks!

**Closed** 2022-10-10 08:40 UTC
Labels: bug
