### ISSUE TITLE
{Feature Request} Dark Mode?

### ISSUE THREAD

**Issue by NorkDorf** [crystalidea/uninstall-tool#105] opened 2022-07-23 07:41 UTC
Would be nice to have a default dark mode. I have tried to change the colors to black and it just doesn't look right. The white is just hard on the eyes at night and I prefer dark mode on most things.

**Comment by kleuter** [comment] 2022-07-30 14:50
Duplicate of https://github.com/crystalidea/uninstall-tool/issues/104

**Comment by kleuter** [comment] 2022-08-08 07:09
Test build, please give your feedback, thanks
[uninstalltool_setup.zip](https://github.com/crystalidea/uninstall-tool/files/9276819/uninstalltool_setup.zip)

**Comment by NorkDorf** [comment] 2022-08-14 23:01
Just tested it and I freaking love it! I know others will too!

**Comment by kleuter** [comment] 2022-08-16 14:06
Thanks! Will roll up the update soon

**Closed** 2022-08-16 14:54 UTC
