### ISSUE TITLE
Opera Browser 64-bit identify error

### ISSUE THREAD

**Issue by vndroid** [crystalidea/uninstall-tool#112] opened 2022-09-09 20:53 UTC
Use the official installer from https://get.opera.com/ftp/pub/opera/desktop/ , such as `Opera_90.0.4480.84_Setup_x64.exe`

But display [Opera Stable 90.0.4480.84 (32-bit)] in Uninstall Tool 3.6.1.

Please fix this error.

OS: Windows 11

**Comment by kleuter** [comment] 2023-03-09 10:30
Duplicate of https://github.com/crystalidea/uninstall-tool/issues/126

**Closed by kleuter** 2023-03-09 10:30 UTC
